[package]
name = "async_sqs_fn"
version = "0.1.0"
edition = "2024"

[dependencies]
app = { path = "../app" }
tokio = { version = "1", features = ["full"] }
lambda_runtime = "1.0"
anyhow = "1.0"
serde_json = "1.0"
